name: CI/CD Pipeline for React App

# This pipeline will trigger on push to the main branch and on pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React application
      - name: Build the application
        run: npm run build

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t yourusername/sample-app .

      # Step 6: Notify on success (Google Chat)
      - name: Notify on success
        if: ${{ success() }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          --data '{"text": "Deployment successful!"}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

      # Step 7: Notify on failure (Google Chat)
      - name: Notify on failure
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          --data '{"text": "Deployment failed!"}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
